trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 0
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Submodules'
  - script: ./scripts/ci-init.sh
    displayName: 'Rust setup'
  - script: cargo test --release --all
    displayName: 'Run tests'
  - script: cargo build --release
    displayName: 'Build artifacts'
  - script: |
      rustup target add x86_64-pc-windows-gnu
      cargo build --release --target x86_64-pc-windows-gnu
    displayName: 'Windows artifacts'

- job: MacOS
  pool:
    vmImage: 'macOS-latest'
  timeoutInMinutes: 0
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Submodules'
  - script: ./scripts/ci-init.sh
    displayName: 'Rust setup'
  - script: |
      source ~/.cargo/env
      cargo test --release --all
    displayName: 'Run tests'
  - script: |
      source ~/.cargo/env
      cargo build --release
    displayName: 'Build artifacts'
