trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 0
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Submodules'
  - script: ./scripts/ci-init.sh
    displayName: 'Rust setup'
  - script: cargo test --release --all
    displayName: 'Run tests'
  - script: cargo build --release
    displayName: 'Build artifacts'

- job: MacOS
  pool:
    vmImage: 'macOS-latest'
  timeoutInMinutes: 0
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Submodules'
  - script: ./scripts/ci-init.sh
    displayName: 'Rust setup'
  - script: |
      source ~/.cargo/env
      cargo test --release --all
    displayName: 'Run tests'
  - script: |
      source ~/.cargo/env
      cargo build --release
    displayName: 'Build artifacts'

- job: Windows
  pool:
    vmImage: 'windows-latest'
  timeoutInMinutes: 0
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Submodules'
  - script: |
      set CARGO_HOME=%USERPROFILE%\.cargo
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain stable
      set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
      rustup update nightly
      rustup update stable
      rustup target add wasm32-unknown-unknown --toolchain nightly
      cargo +nightly install --git https://github.com/alexcrichton/wasm-gc --force
    displayName: 'Rust setup'
  - script: cargo test --release --all
    displayName: 'Run tests'
  - script: cargo build --release
    displayName: 'Build artifacts'
