trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ./scripts/ci-ubuntu-init.sh
  displayName: 'Rust setup'

- script: cargo test --release --all
  displayName: 'Run tests'

- script: cargo build --release
  displayName: 'Build artifacts'
