trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 0
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Submodules'
  - script: ./scripts/ci-init.sh
    displayName: 'Rust setup'
  - script: cargo test --release --all
    displayName: 'Run tests'
  - script: cargo build --release
    displayName: 'Build artifacts'
  - script: |
      cp target/release/kulupu target/release/kulupu-linux
    displayName: 'Finalize artifacts'
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'target/release'
      contents: 'kulupu-linux'
      targetFolder: $(Build.ArtifactStagingDirectory)

- job: MacOS
  pool:
    vmImage: 'macOS-latest'
  timeoutInMinutes: 0
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Submodules'
  - script: ./scripts/ci-init.sh
    displayName: 'Rust setup'
  - script: |
      source ~/.cargo/env
      cargo test --release --all
    displayName: 'Run tests'
  - script: |
      source ~/.cargo/env
      cargo build --release
    displayName: 'Build artifacts'
  - script: |
      cp target/release/kulupu target/release/kulupu-macos
    displayName: 'Finalize artifacts'
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'target/release'
      contents: 'kulupu-macos'
      targetFolder: $(Build.ArtifactStagingDirectory)
