trigger:
- master

jobs:
- job: Linux

  pool:
    vmImage: 'ubuntu-latest'

  timeoutInMinutes: 0

  steps:
  - script: git submodule update --init --recursive
    displayName: 'Submodules'

  - script: ./scripts/ci-ubuntu-init.sh
    displayName: 'Rust setup'

  - script: cargo test --release --all
    displayName: 'Run tests'

  - script: cargo build --release
    displayName: 'Build artifacts'
