[package]
name = "kulupu-runtime"
version = "4.0.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-std = { path = "../vendor/substrate/primitives/std", default-features = false }
sp-io = { path = "../vendor/substrate/primitives/io", default-features = false }
sp-version = { path = "../vendor/substrate/primitives/version", default-features = false }
sp-core = { path = "../vendor/substrate/primitives/core", default-features = false }
sp-runtime = { path = "../vendor/substrate/primitives/runtime", default-features = false }
sp-offchain = { path = "../vendor/substrate/primitives/offchain", default-features = false }
sp-consensus-pow = { path = "../vendor/substrate/primitives/consensus/pow", default-features = false }
sp-session = { path = "../vendor/substrate/primitives/session", default-features = false }
sp-api = { path = "../vendor/substrate/primitives/api", default-features = false }
sp-block-builder = { path = "../vendor/substrate/primitives/block-builder", default-features = false }
sp-transaction-pool = { path = "../vendor/substrate/primitives/transaction-pool", default-features = false }
sp-inherents = { path = "../vendor/substrate/primitives/inherents", default-features = false }
frame-support = { path = "../vendor/substrate/frame/support", default-features = false }
frame-executive = { path = "../vendor/substrate/frame/executive", default-features = false }
frame-system = { path = "../vendor/substrate/frame/system", default-features = false }
pallet-balances = { path = "../vendor/substrate/frame/balances", default-features = false }
pallet-utility = { path = "../vendor/substrate/frame/utility", default-features = false }
pallet-indices = { path = "../vendor/substrate/frame/indices", default-features = false }
pallet-timestamp = { path = "../vendor/substrate/frame/timestamp", default-features = false }
pallet-transaction-payment = { path = "../vendor/substrate/frame/transaction-payment", default-features = false }
pallet-randomness-collective-flip = { path = "../vendor/substrate/frame/randomness-collective-flip", default-features = false }
pallet-democracy = { path = "../vendor/substrate/frame/democracy", default-features = false }
pallet-collective = { path = "../vendor/substrate/frame/collective", default-features = false }
pallet-elections-phragmen = { path = "../vendor/substrate/frame/elections-phragmen", default-features = false }
pallet-membership = { path = "../vendor/substrate/frame/membership", default-features = false }
pallet-treasury = { path = "../vendor/substrate/frame/treasury", default-features = false }
pallet-scheduler = { path = "../vendor/substrate/frame/scheduler", default-features = false }
pallet-identity = { path = "../vendor/substrate/frame/identity", default-features = false }
pallet-rewards = { path = "../frame/rewards", default-features = false }
pallet-eras = { path = "../frame/eras", default-features = false }
pallet-difficulty = { path = "../frame/difficulty", default-features = false }
kulupu-primitives = { path = "../primitives", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.5", path = "../vendor/substrate/utils/wasm-builder-runner" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-version/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-offchain/std",
	"sp-consensus-pow/std",
	"sp-session/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	"sp-inherents/std",
	"frame-support/std",
	"frame-executive/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-utility/std",
	"pallet-indices/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-randomness-collective-flip/std",
	"pallet-democracy/std",
	"pallet-collective/std",
	"pallet-elections-phragmen/std",
	"pallet-membership/std",
	"pallet-treasury/std",
	"pallet-scheduler/std",
	"pallet-identity/std",
	"pallet-rewards/std",
	"pallet-eras/std",
	"pallet-difficulty/std",
	"kulupu-primitives/std",
]
