[package]
name = "kulupu-randomx-sys"
description = "FFI bindings for RandomX"
license = "BSD-3-Clause"
version = "2.2.0"
authors = ["Wei Tang <wei@that.world>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.54"
cmake = "0.1"
